2024-08-10 23:22:07.900 +05:30 [INF] Logger Intialized at:10-Aug-24 11:22:07 PM
2024-08-10 23:22:16.448 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:22:16 PM
2024-08-10 23:22:17.208 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 3758: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
2024-08-10 23:22:17.208 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:22:17.208 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 162: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.ExecuteGenerationAsync(Boolean value, Boolean IsCodeGeneration)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.SetCodeGeneratedAsync(Boolean value)
2024-08-10 23:23:57.928 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:23:57.928 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:23:57.928 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:33:58.442 +05:30 [INF] Logger Intialized at:10-Aug-24 11:33:58 PM
2024-08-10 23:34:06.871 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:34:06 PM
2024-08-10 23:34:07.518 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 162: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.ExecuteGenerationAsync(Boolean value, Boolean IsCodeGeneration)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.SetCodeGeneratedAsync(Boolean value)
2024-08-10 23:34:07.518 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:34:07.518 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 3758: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
2024-08-10 23:34:46.786 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:34:46 PM
2024-08-10 23:34:46.814 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:34:46.814 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 3758: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
2024-08-10 23:34:46.815 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 162: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.ExecuteGenerationAsync(Boolean value, Boolean IsCodeGeneration)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.SetCodeGeneratedAsync(Boolean value)
2024-08-10 23:35:48.817 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:35:48.817 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:35:48.817 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:36:21.829 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:36:21 PM
2024-08-10 23:36:21.849 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:36:21.849 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 3758: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
2024-08-10 23:36:21.850 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 162: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.ExecuteGenerationAsync(Boolean value, Boolean IsCodeGeneration)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.SetCodeGeneratedAsync(Boolean value)
2024-08-10 23:36:22.192 +05:30 [INF] Issue Creation Request Failure Status:
2024-08-10 23:36:22.192 +05:30 [INF] Issue Creation Request Failure Status:
2024-08-10 23:36:22.193 +05:30 [INF] Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlhYmJlNGIwLTZmMTMtNDk1ZC1hOTc4LTIzYTk4NmJlZjJhOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJYU0lzc3VlRWRpdG9yIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiWHBlcnRzdHVkaW8iLCJXZWJBUElDb250cm9sbGVyIjpbIlJlcG9ydEV4Y2VwdGlvbkNvbnRyb2xsZXIiLCJQcm9kdWN0Q29tcG9uZW50c0NvbnRyb2xsZXIiXSwiV2ViQ29tcG9uZW50IjpbIlJlcG9ydEV4Y2VwdGlvbiIsIlJlcG9ydEV4Y2VwdGlvbkJhc2VQYWdlIiwiUmVwb3J0RXhjZXB0aW9uQ3JlYXRlIiwiUmVwb3J0RXhjZXB0aW9uRWRpdCIsIlJlcG9ydEV4Y2VwdGlvblZpZXciLCJQcm9kdWN0Q29tcG9uZW50cyJdLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFZGl0b3IiLCJleHAiOjE3MjMzOTk1ODIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.HAi2T77fZS1pXPKISEuHEj3pDxaHLH0PMkkZvm6WCJ0
2024-08-10 23:36:22.193 +05:30 [INF] Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjlhYmJlNGIwLTZmMTMtNDk1ZC1hOTc4LTIzYTk4NmJlZjJhOSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJYU0lzc3VlRWRpdG9yIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiWHBlcnRzdHVkaW8iLCJXZWJBUElDb250cm9sbGVyIjpbIlJlcG9ydEV4Y2VwdGlvbkNvbnRyb2xsZXIiLCJQcm9kdWN0Q29tcG9uZW50c0NvbnRyb2xsZXIiXSwiV2ViQ29tcG9uZW50IjpbIlJlcG9ydEV4Y2VwdGlvbiIsIlJlcG9ydEV4Y2VwdGlvbkJhc2VQYWdlIiwiUmVwb3J0RXhjZXB0aW9uQ3JlYXRlIiwiUmVwb3J0RXhjZXB0aW9uRWRpdCIsIlJlcG9ydEV4Y2VwdGlvblZpZXciLCJQcm9kdWN0Q29tcG9uZW50cyJdLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFZGl0b3IiLCJleHAiOjE3MjMzOTk1ODIsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0IiwiYXVkIjoibG9jYWxob3N0In0.HAi2T77fZS1pXPKISEuHEj3pDxaHLH0PMkkZvm6WCJ0
2024-08-10 23:36:22.194 +05:30 [INF] HTTP Status Code: InternalServerError
2024-08-10 23:36:22.194 +05:30 [INF] HTTP Status Code: InternalServerError
2024-08-10 23:36:22.194 +05:30 [INF] Response Content: 
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Error</title>
    <link href="/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/app.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <div class="content px-4">
            <h1 class="text-danger">Error.</h1>
            <h2 class="text-danger">An error occurred while processing your request.</h2>


            <h3>Development Mode</h3>
            <p>
                Swapping to the <strong>Development</strong> environment displays detailed information about the error that occurred.
            </p>
            <p>
                <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
                It can result in displaying sensitive information from exceptions to end users.
                For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
                and restarting the app.
            </p>
        </div>
    </div>
</body>

</html>

2024-08-10 23:36:22.194 +05:30 [INF] ReasonPharase: Internal Server Error
2024-08-10 23:36:22.194 +05:30 [INF] Response Content: 
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>Error</title>
    <link href="/css/bootstrap/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/app.css" rel="stylesheet" />
</head>

<body>
    <div class="main">
        <div class="content px-4">
            <h1 class="text-danger">Error.</h1>
            <h2 class="text-danger">An error occurred while processing your request.</h2>


            <h3>Development Mode</h3>
            <p>
                Swapping to the <strong>Development</strong> environment displays detailed information about the error that occurred.
            </p>
            <p>
                <strong>The Development environment shouldn't be enabled for deployed applications.</strong>
                It can result in displaying sensitive information from exceptions to end users.
                For local debugging, enable the <strong>Development</strong> environment by setting the <strong>ASPNETCORE_ENVIRONMENT</strong> environment variable to <strong>Development</strong>
                and restarting the app.
            </p>
        </div>
    </div>
</body>

</html>

2024-08-10 23:36:22.194 +05:30 [INF] ReasonPharase: Internal Server Error
2024-08-10 23:36:27.924 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:36:27.924 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:36:27.924 +05:30 [ERR] An exception occurred in XSExceptionLogger at line 160: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger.SaveException(clsReportException entity)
2024-08-10 23:36:47.231 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:36:47 PM
2024-08-10 23:36:47.453 +05:30 [INF] Metadata Extraction completed at:10-Aug-24 11:36:47 PM
2024-08-10 23:48:36.523 +05:30 [INF] Logger Intialized at:10-Aug-24 11:48:36 PM
2024-08-10 23:48:40.598 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:48:40 PM
2024-08-10 23:48:41.349 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:48:50.539 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:48:50 PM
2024-08-10 23:48:50.583 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 5393: Object reference not set to an instance of an object.
XpertStudio.Framework.Exceptions.XSException: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
2024-08-10 23:48:50.583 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 3758: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
2024-08-10 23:48:50.583 +05:30 [ERR] An exception occurred in D:\Official\XpertGitHubProjects\XpertStudio\XpertStudio.Framework.FormDesigner\Components\XSMetadataExtractor.cs at line 162: Object reference not set to an instance of an object.
XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> XpertStudio.Framework.WinFormUI.Components.XSExceptionLogger: Object reference not set to an instance of an object.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateXSBindingSource(IXpertDataSource ds, String Control_Name, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass6_0.<<ValidateForm>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ValidateForm(IXpertDomainBaseForm frm, Boolean IsMigration, List`1 MigrationLog)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass4_0.<<GetFormData>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.GetFormData(IXpertDomainBaseForm frm, clsFormDesigner _currForm)
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.<>c__DisplayClass2_0.<<ExtractMetadata>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   --- End of inner exception stack trace ---
   at XpertStudio.Framework.WinFormUI.Components.XSMetadataExtractor.ExtractMetadata(IXpertBaseForm form)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.ExecuteGenerationAsync(Boolean value, Boolean IsCodeGeneration)
   at XpertStudio.Framework.WinFormUI.XpertBaseForm.SetCodeGeneratedAsync(Boolean value)
2024-08-10 23:56:03.922 +05:30 [INF] Logger Intialized at:10-Aug-24 11:56:03 PM
2024-08-10 23:56:07.906 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:56:07 PM
2024-08-10 23:57:11.165 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:57:11 PM
2024-08-10 23:57:16.426 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:57:16 PM
2024-08-10 23:57:37.635 +05:30 [INF] Metadata Extraction Started at:10-Aug-24 11:57:37 PM
2024-08-10 23:57:37.769 +05:30 [INF] Metadata Extraction completed at:10-Aug-24 11:57:37 PM
2024-08-11 00:10:28.074 +05:30 [INF] Logger Intialized at:11-Aug-24 12:10:28 AM
2024-08-11 00:10:35.194 +05:30 [INF] Metadata Extraction Started at:11-Aug-24 12:10:35 AM
2024-08-11 00:10:35.691 +05:30 [INF] Metadata Extraction completed at:11-Aug-24 12:10:35 AM
2024-08-11 01:32:38.173 +05:30 [INF] Logger Intialized at:11-Aug-24 1:32:38 AM
2024-08-11 01:32:46.388 +05:30 [INF] Metadata Extraction Started at:11-Aug-24 1:32:46 AM
2024-08-11 01:32:47.245 +05:30 [INF] Metadata Extraction completed at:11-Aug-24 1:32:47 AM
